

# This file was *autogenerated* from the file curve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1009 = Integer(1009); _sage_const_0 = Integer(0); _sage_const_11 = Integer(11); _sage_const_1 = Integer(1)
max_coordinate = _sage_const_1009 
assert max_coordinate.is_prime()
Coordinates = FiniteField(max_coordinate)
Curve = EllipticCurve([Coordinates(_sage_const_0 ), Coordinates(_sage_const_11 )])

number_points = Curve.order()
assert number_points.is_prime()
max_scalar = number_points
Scalars = FiniteField(max_scalar)

Zero = Curve(_sage_const_0 )
One = Curve.gens()[_sage_const_0 ]
zero = Scalars(_sage_const_0 )
one = Scalars(_sage_const_1 )

